/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as MangaRouteImport } from './routes/manga'
import { Route as NovelsRouteImport } from './routes/novels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaRoute = MangaRouteImport.update({
  id: '/manga',
  path: '/manga',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsRoute = NovelsRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/manga': typeof MangaRoute
  '/novels': typeof NovelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/manga': typeof MangaRoute
  '/novels': typeof NovelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/manga': typeof MangaRoute
  '/novels': typeof NovelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime' | '/manga' | '/novels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime' | '/manga' | '/novels'
  id: '__root__' | '/' | '/anime' | '/manga' | '/novels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  MangaRoute: typeof MangaRoute
  NovelsRoute: typeof NovelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga': {
      id: '/manga'
      path: '/manga'
      fullPath: '/manga'
      preLoaderRoute: typeof MangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels': {
      id: '/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof NovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  MangaRoute: MangaRoute,
  NovelsRoute: NovelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
